Repository UMC-Archive/Back, pull requests merged in 2025-02, with the labels that each got.

#99 [feature] 유저 재생 기록 swagger 추가
  src/controllers/user.controller.js
Labels: :sparkles: feature

#101 [feature] 연도별 추천 노래 수정
  src/controllers/music.controller.js
  src/repositories/music.repository.js
  src/services/music.service.js
Labels: :sparkles: feature

#103 [feature] 숨겨진 명곡 앨범 추가
  src/billboard.js
  src/controllers/music.controller.js
  src/dtos/music.dto.js
  src/services/music.service.js
Labels: :sparkles: feature

#105 [fix] 다른 이미지 적용 문제
  src/controllers/music.controller.js
  src/lastfm.js
  src/middleware/jwt.js
  src/repositories/music.repository.js
  src/services/music.service.js
Labels: :bug: bug, :sparkles: feature

#110 [feature] 추천 알고리즘 수정
  prisma/migrations/20250202093747_/migration.sql
  src/lastfm.js
  src/services/music.service.js
Labels: :bug: bug, :sparkles: feature

#121 [feature] 음악 재생에 음악 장르 비동기 추가
  src/controllers/user.controller.js
  src/middleware/gpt.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :sparkles: feature

#123 [feature] 다른 비슷한 아티스트 추가
  src/controllers/music.controller.js
  src/index.js
  src/lastfm.js
  src/middleware/jwt.js
  src/repositories/music.repository.js
  src/services/music.service.js
Labels: :sparkles: feature

#125 [feature] 이 아티스트의 다른 앨범
  src/controllers/music.controller.js
  src/index.js
  src/middleware/jwt.js
  src/services/music.service.js
Labels: :sparkles: feature

#130 [feature] 모든 정보 조회하기
  config/response.status.js
  src/controllers/music.controller.js
  src/index.js
  src/middleware/jwt.js
  src/services/music.service.js
Labels: :sparkles: feature

#135 [feature] mbid 값 수정
  src/lastfm.js
  src/services/music.service.js
Labels: :bug: bug, :sparkles: feature

#137 [feature] history image s3
  package-lock.json
  package.json
  src/repositories/s3.repository.js
Labels: :sparkles: feature

#139 [feature] swagger 작성
  src/controllers/music.controller.js
  src/index.js
Labels: :memo: docs, :sparkles: feature

#140 [feature] library 관련 api 및 스웨거
  config/response.status.js
  src/controllers/library.controller.js
  src/index.js
  src/repositories/library.repository.js
  src/services/library.service.js
Labels: :sparkles: feature

#142 [feature] 빠른 선곡 추가
  src/controllers/music.controller.js
  src/index.js
  src/repositories/music.repository.js
  src/services/music.service.js
Labels: :sparkles: feature

#144 [fix] similar artist 응답 값 앨범 추가
  src/controllers/music.controller.js
  src/services/music.service.js
Labels: :sparkles: feature

#152 refactoring code that get album track list and edit swagger docs
  src/controllers/music.controller.js
  src/lastfm.js
  src/repositories/music.repository.js
Labels: :recycle: refactor

#154 [feature] 앨범 조회 아이튠즈 제거
  src/controllers/user.controller.js
  src/itunes.js
  src/repositories/music.repository.js
  src/services/music.service.js
Labels: :sparkles: feature

#155 add user recent music & fix timehistory
  src/controllers/user.controller.js
  src/index.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :memo: docs, :sparkles: feature

#157 fix user swagger & fix profile api
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :memo: docs, :sparkles: feature

#160 [feature] 중복된 음악, 보관함 조회 id값 반환
  prisma/migrations/migration_lock.toml
  src/dtos/library.dto.js
  src/repositories/library.repository.js
  src/repositories/music.repository.js
  src/services/music.service.js
Labels: :sparkles: feature

#162 [fix] 숨겨진 명곡 수정
  prisma/migrations/migration_lock.toml
  src/services/music.service.js
Labels: :bug: bug, :sparkles: feature

#165 [feature] https 적용
  package-lock.json
  package.json
  src/index.js
Labels: :sparkles: feature

#167 [feature] library swagger 수정
  src/controllers/library.controller.js
Labels: :sparkles: feature

#169 [fix] 유저 프로필 변경 닉네임 수정
  src/controllers/user.controller.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :sparkles: feature

#171 Feature/users play
  src/controllers/user.controller.js
  src/index.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :memo: docs, :sparkles: feature

#173 [fix] 장르 정보 앞에 대문자 처리
  src/repositories/s3.repository.js
Labels: :sparkles: feature

#177 Feature/popular artist
  src/controllers/music.controller.js
  src/index.js
  src/lastfm.js
  src/services/music.service.js
Labels: :memo: docs, :sparkles: feature

#179 fix user play
  src/controllers/user.controller.js
  src/repositories/user.repository.js
  src/services/music.service.js
Labels: :memo: docs, :sparkles: feature

#180 [feature] main cd 제작 및 artist 오류 수정
  src/controllers/music.controller.js
  src/index.js
  src/repositories/music.repository.js
  src/services/music.service.js
Labels: :sparkles: feature

#184 fix user play & recent api
  src/controllers/user.controller.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :memo: docs, :sparkles: feature

#186 [feature] 앨범 타이틀 추가
  src/controllers/user.controller.js
  src/index.js
  src/repositories/user.repository.js
Labels: :sparkles: feature

#188 [feature] releaseTime 추가
  src/controllers/user.controller.js
  src/repositories/user.repository.js
Labels: :sparkles: feature

#192 [feature] 보관함에 앨범 추가
  prisma/schema.prisma
  src/controllers/library.controller.js
  src/dtos/library.dto.js
  src/repositories/library.repository.js
Labels: :sparkles: feature

#207 fix play api
  src/repositories/user.repository.js
Labels: :sparkles: feature

#208 [fix] 숨겨진 명곡 오류 수정
  src/services/music.service.js
Labels: :bug: bug

#211 [fix] 메인 cd s3업로드 문제
  src/services/music.service.js
Labels: :bug: bug

#217 [refactor] 당신을 위한 곡 앨범 개수
  src/services/music.service.js
Labels: :recycle: refactor

#220 [feature] 코딩 컨벤션
  README.md
  config/response.js
  src/billboard.js
  src/controllers/music.controller.js
  src/controllers/user.controller.js
  src/dtos/music.dto.js
  src/dtos/user.dto.js
  src/middleware/jwt.js
  src/repositories/library.repository.js
  src/repositories/s3.repository.js
  src/repositories/user.repository.js
  src/services/library.service.js
  src/services/music.service.js
  src/services/user.service.js
  src/spotify.js
Labels: :sparkles: feature
