Repository UMC-Archive/Back, pull requests merged in 2025-01, with the labels that each got.

#10 [feature] 회원가입 이메일 인증 관련 api
  config/response.js
  config/response.status.js
  package-lock.json
  package.json
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/index.js
  src/middleware/email.js
  src/middleware/encrypt.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: feature

#19 add music swagger
  src/controllers/music.controller.js
  src/index.js
Labels: :memo: docs

#21 [feature] 정보 가져오기
  package-lock.json
  package.json
  src/auth.config.js
  src/controllers/music.controller.js
  src/controllers/user.controller.js
  src/dtos/music.dto.js
  src/index.js
  src/lastfm.js
  src/repositories/music.repository.js
  src/services/music.service.js
Labels: :sparkles: feature

#23 [feature] 숨겨진 명곡 가져오기
  package-lock.json
  package.json
  prisma/migrations/20250101115128_/migration.sql
  prisma/migrations/20250110060457_/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/billboard.js
  src/controllers/music.controller.js
  src/dtos/music.dto.js
  src/index.js
  src/lastfm.js
  src/repositories/music.repository.js
  src/services/music.service.js
Labels: :sparkles: feature, :recycle: refactor

#24 [fix] Email Auth change gmail
  src/middleware/email.js
Labels: :sparkles: feature

#26 [feature] spotify->itunes 변경
  prisma/migrations/migration_lock.toml
  src/auth.config.js
  src/billboard.js
  src/index.js
  src/itunes.js
  src/lastfm.js
  src/repositories/music.repository.js
  src/services/music.service.js
Labels: :sparkles: feature

#28 [feature] 추천곡, 앨범 조회 (연도별)
  prisma/schema.prisma
  src/auth.config.js
  src/billboard.js
  src/controllers/music.controller.js
  src/controllers/user.controller.js
  src/index.js
  src/itunes.js
  src/lastfm.js
  src/repositories/music.repository.js
  src/services/music.service.js
Labels: :sparkles: feature

#35 [feature] 라이브러리 DB 추가
  prisma/schema.prisma
Labels: :sparkles: feature

#39 [feature] 이미지 업로드 api 추가
  package-lock.json
  package.json
  src/config/s3.config.js
  src/controllers/user.controller.js
  src/index.js
  src/repositories/s3.repository.js
  src/services/user.service.js
Labels: :sparkles: feature

#42 [feature] 회원가입에 library 추가
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :sparkles: feature

#45 [feature] swagger 응답 수정
  config/response.status.js
  src/controllers/music.controller.js
  src/controllers/user.controller.js
  src/repositories/s3.repository.js
Labels: :sparkles: feature

#50 [feature] 음악 재생 기록 추가
  prisma/schema.prisma
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/index.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :sparkles: feature

#53 [feature] gpt api code
  config/response.status.js
  package-lock.json
  package.json
  src/controllers/user.controller.js
  src/middleware/gpt.js
  src/repositories/user.repository.js
Labels: :sparkles: feature

#55 [feature] nomination gpt
  src/repositories/music.repository.js
  src/services/music.service.js
Labels: :sparkles: feature

#62 [feature] 회원가입 이미지 업로드 통합
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/index.js
  src/repositories/s3.repository.js
  src/services/user.service.js
Labels: :sparkles: feature

#64 [feature] curation 추가 및 prisma 수정
  prisma/schema.prisma
  src/controllers/user.controller.js
  src/itunes.js
  src/repositories/music.repository.js
  src/services/music.service.js
  src/services/user.service.js
Labels: :sparkles: feature

#69 [feature] swagger 수정
  src/controllers/music.controller.js
  src/controllers/user.controller.js
Labels: :memo: docs

#73 feat:prisma 수정 및 코드 수정
  package-lock.json
  package.json
  prisma/migrations/20250129083316_/migration.sql
  prisma/schema.prisma
  src/controllers/music.controller.js
  src/controllers/user.controller.js
  src/index.js
  src/middleware/jwt.js
  src/repositories/music.repository.js
  src/services/music.service.js
Labels: :sparkles: feature

#75 [feature] userId 변경
  prisma/migrations/20250129083316_/migration.sql
  src/billboard.js
  src/controllers/music.controller.js
  src/controllers/user.controller.js
  src/dtos/music.dto.js
  src/dtos/user.dto.js
  src/middleware/jwt.js
  src/repositories/music.repository.js
  src/services/music.service.js
Labels: :sparkles: feature

#77 [feature] 회원가입 수정
  config/response.status.js
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/repositories/s3.repository.js
  src/services/user.service.js
Labels: :sparkles: feature

#83 [feature] 장르 이미지 s3에서 가져오기
  src/controllers/music.controller.js
  src/index.js
  src/repositories/music.repository.js
  src/repositories/s3.repository.js
  src/services/music.service.js
Labels: :sparkles: feature

#89 [feature] swagger 및 코드 수정
  src/controllers/music.controller.js
  src/middleware/jwt.js
  src/services/music.service.js
Labels: :sparkles: feature
